# Generated by Django 5.0.2 on 2024-05-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocapturecomments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tocapturecomments',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='tocapturecomments',
            old_name='start_date',
            new_name='start',
        ),
    ]
