# Generated by Django 5.0.2 on 2024-05-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocapturecomments', '0002_rename_end_date_tocapturecomments_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tocapturecomments',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tocapturecomments',
            old_name='start',
            new_name='start_date',
        ),
    ]
