# Generated by Django 5.0.2 on 2024-06-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocapturecomments', '0004_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
